画面作成(アカウント削除)
schwarzwald0906/My_Gourmet pull request #20
Opened 2024-01-20 01:04 UTC by finish-cloud

ログイン・ログアウト・アカウント削除の画面を作成しました。
参考：https://zenn.dev/joo_hashi/scraps/6fea4ca557c569

![Screenshot_20240120_093225](https://github.com/schwarzwald0906/My_Gourmet/assets/57353856/8c7803c3-7363-46da-bcad-12ec7fb40f9d)
![Screenshot_20240117_013026](https://github.com/schwarzwald0906/My_Gourmet/assets/57353856/1ee955f0-5c8a-4610-98ff-89fab54f19c3)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-20 at 09 29 00](https://github.com/schwarzwald0906/My_Gourmet/assets/57353856/b92a1054-6201-4f3d-b089-a77397436a86)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-20 at 09 28 26](https://github.com/schwarzwald0906/My_Gourmet/assets/57353856/ef2433db-df23-45a0-8d56-a0ed3819992b)

2024-01-20 04:55 UTC, schwarzwald0906 commented
@finish-cloud 
CIで落ちちゃってるので、修正お願いいたします！
また、マップのタブは、今後入れますが、1stリリースでは入れないので、いったん削除で大丈夫です。
可能であれば、そこだけスタッシュしておいて、あとでタブを入れられるようにしておくと楽かと！

最後に、Masakiさんもレビュアーに含めてください！

2024-01-21 03:34 UTC, masa-tokyo reviewed
@finish-cloud 
早速ご対応ありがとうございます！！

以下二点ご確認お願いします！
- iOS関連のファイルは一旦revertコミットで戻してもらえると助かります！
現状の1stリリースではこちら対応しなくて、環境によってビルド出来なかったりするので、後日の対応に出来たらと思います🙏

- ページ構成について
`login.dart`と`logout.dart`は、一つのページ（`my_page.dart`とか）で良いかなと思います！実際には、このログイン or ログアウトボタンを現状のログイン状況によって切り替えるような実装になるイメージです💡

2024-01-24 11:25 UTC, masa-tokyo reviewed
@finish-cloud 

こちら変更ありがとうございます！
iosディレクトリ内だけ少し差分出てしまっているので、元の状態にコピペで良いので戻した上でプッシュいただけると助かります🙌

2024-01-25 12:50 UTC, schwarzwald0906 requested changes
ios配下の差分が消えていません。。。

2024-01-25 12:53 UTC, schwarzwald0906 approved these changes

2024-01-25 12:55 UTC, schwarzwald0906 commented
余計な差分は消せなかったですかね、、、？
実装に影響はないので、今回は多めに見ます。

2024-01-25 12:56 UTC, merged