PRテンプレートを修正
schwarzwald0906/My_Gourmet pull request #49
Opened 2024-04-15 11:57 UTC by masa-tokyo

@schwarzwald0906 

こちらコメント部分(編集中だけ表示したい）を微修正しました！

2024-04-15 13:07 UTC, schwarzwald0906 commented on .github/pull_request_template.md
@masa-tokyo 
ここすみません、下記の通りでした。修正していただけると！
- [ ] : 
- [x] :

2024-04-15 14:17 UTC, masa-tokyo commented on .github/pull_request_template.md
@schwarzwald0906 

なるほど、スペースいらなかったんですね！修正しました！

2024-04-15 22:33 UTC, schwarzwald0906 requested changes

2024-04-15 22:33 UTC, schwarzwald0906 commented on .github/pull_request_template.md
> +[] 補足があった方が良い/重点的にレビューが欲しい箇所にGitHub上でコメントをしたか
```suggestion
- [ ] 実装完了後、問題が起こっていないか実際に動作確認したか  
- [ ] 補足があった方が良い/重点的にレビューが欲しい箇所にGitHub上でコメントをしたか
```

`[ ]`はそのままで、その前に`- `が抜けていたということです

`- [ ]`とやると下記のようになります
- [ ] : チェック1

2024-04-15 22:34 UTC, schwarzwald0906 commented on .github/pull_request_template.md
@masa-tokyo 
すみません、コメントの仕方が悪かったと思うので、書き直しました。
こちら参照してもらえると🙏
https://github.com/schwarzwald0906/My_Gourmet/pull/49#discussion_r1566506495

2024-04-16 13:12 UTC, masa-tokyo commented on .github/pull_request_template.md
@schwarzwald0906 

ありがとうございます！反映しました！

2024-04-17 01:37 UTC, schwarzwald0906 approved these changes
LGTMです！

2024-04-17 01:37 UTC, merged